import type { Metadata } from "next";
import "./globals.css";
import {css} from "@styled-system/css";

export const metadata: Metadata = {
  title: "기록은 나의 빛",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={css({ bg: 'zinc.900' })}>{children}</body>
    </html>
  );
}
