import type { Metadata } from 'next';
import './globals.css';
import { css } from '@styled-system/css';
import Providers from '@/components/system/Providers';
import Header from '@/components/base/Header';
import { container, containerRaw } from '@/lib/styles/container';
import Footer from '@/components/base/Footer';
import getIsAdmin from '@/app/_actions/getIsAdmin';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';

export const metadata: Metadata = {
  title: '기록은 나의 빛',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const isAdmin = getIsAdmin();

  console.log(session);

  return (
    <html lang="ko" data-theme="dark" suppressHydrationWarning>
      <body className={styledBody}>
        <Providers>
          <div className={rootBlock}>
            <Header isAdmin={isAdmin} />
            <div className={mainBlock}>{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}

const styledBody = css({
  bg: 'bg_page1',
});

const rootBlock = css({
  display: 'flex',
  flexDir: 'column',
  minH: '100dvh',
});

const mainStyle = css.raw({
  flex: 1,
  width: '100%',
  mb: 20,
});

const mainBlock = css(mainStyle, containerRaw);
