import type { Metadata } from 'next';
import './globals.css';
import { css } from '@styled-system/css';
import Providers from '@/components/system/Providers';
import getIsAdmin from '@/app/_actions/getIsAdmin';
import UserStoreProvider from '@/components/auth/UserStoreProvider';
import getUser from '@/app/_actions/getUser';
import Layout from '@/components/base/Layout';

export const metadata: Metadata = {
  title: '기록은 나의 빛',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const { isAdmin } = getIsAdmin();

  return (
    <html lang="ko" data-theme="dark" suppressHydrationWarning>
      <body className={styledBody}>
        <Providers>
          <UserStoreProvider user={user}>
            <Layout isAdmin={isAdmin}>{children}</Layout>
          </UserStoreProvider>
        </Providers>
      </body>
    </html>
  );
}

const styledBody = css({
  bg: 'bg_page1',
});
